set_property SRC_FILE_INFO {cfile:c:/Projects/Vivado/Aging/vivado_project/aging-study/aging-study.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc rfile:../aging-study.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Projects/Vivado/Aging/vivado_project/aging-study/aging-study.srcs/constrs_1/imports/digilent-xdc/Nexys-4-DDR-Master.xdc rfile:../aging-study.srcs/constrs_1/imports/digilent-xdc/Nexys-4-DDR-Master.xdc id:2} [current_design]
current_instance design_1_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.100
current_instance
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H17 [get_cells path_OBUF_inst]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U14 [get_cells LED0_OBUF_inst]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N17 [get_cells reset_IBUF_inst]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M18 [get_cells button_IBUF_inst]
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[6].INV}]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[12].INV}]
set_property src_info {type:XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[0].INV}]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[1].INV}]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[7].INV}]
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[2].INV}]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[11].INV}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[5].INV}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[8].INV}]
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[9].INV}]
set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells design_1_i/not_series_0/inst/start_reg]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[3].INV}]
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[4].INV}]
set_property src_info {type:XDC file:2 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[10].INV}]
set_property src_info {type:XDC file:2 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells design_1_i/modern_sensible_0/inst/FF2]
set_property src_info {type:XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[6].INV}]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y92 [get_cells {design_1_i/not_series_0/inst/genblk1[12].INV}]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[0].INV}]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[1].INV}]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[7].INV}]
set_property src_info {type:XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[2].INV}]
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y92 [get_cells {design_1_i/not_series_0/inst/genblk1[11].INV}]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[5].INV}]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y92 [get_cells {design_1_i/not_series_0/inst/genblk1[8].INV}]
set_property src_info {type:XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y92 [get_cells {design_1_i/not_series_0/inst/genblk1[9].INV}]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y91 [get_cells design_1_i/not_series_0/inst/start_reg]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[3].INV}]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y91 [get_cells {design_1_i/not_series_0/inst/genblk1[4].INV}]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y92 [get_cells {design_1_i/not_series_0/inst/genblk1[10].INV}]
set_property src_info {type:XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y92 [get_cells design_1_i/modern_sensible_0/inst/FF2]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_L_CMUX CLBLL_LOGIC_OUTS18  { NR1BEG0 BYP_ALT1 BYP_L1 CLBLL_LL_AX }  ER1BEG1 BYP_ALT5 BYP5 CLBLM_L_BX }  } [get_nets design_1_i/not_series_0/inst/critpath]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells design_1_i/modern_sensible_0/inst/XOR1]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells design_1_i/modern_sensible_0/inst/AND1]
set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells design_1_i/modern_sensible_0/inst/BUF1]
set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells design_1_i/modern_sensible_0/inst/FF1]
set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells design_1_i/modern_sensible_0/inst/FF3]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y92 [get_cells design_1_i/modern_sensible_0/inst/XOR1]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y92 [get_cells design_1_i/modern_sensible_0/inst/AND1]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y91 [get_cells design_1_i/modern_sensible_0/inst/BUF1]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y92 [get_cells design_1_i/modern_sensible_0/inst/FF1]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y92 [get_cells design_1_i/modern_sensible_0/inst/FF3]
