set_property SRC_FILE_INFO {cfile:{/home/dan-alencar/Documents/GitHub/Aging/Vivado Projects/aging-study/aging-study.srcs/constrs_1/imports/digilent-xdc/Nexys-4-DDR-Master.xdc} rfile:../../../aging-study.srcs/constrs_1/imports/digilent-xdc/Nexys-4-DDR-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports CLK100MHZ]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports CA]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports CB]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports CC]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports CD]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports CE]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports CF]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports CG]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports DP]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {AN[0]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {AN[1]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {AN[2]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {AN[3]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {AN[4]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {AN[5]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {AN[6]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {AN[7]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports reset]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports button]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports UARTsend]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports tx]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports direction]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports shift]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H17 [get_cells path_OBUF_inst]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U14 [get_cells LED0_OBUF_inst]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N17 [get_cells reset_IBUF_inst]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M18 [get_cells button_IBUF_inst]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { failure }]; #IO_L24P_T3_RS1_15 Sch=led[1]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C4    IOSTANDARD LVCMOS33 } [get_ports { rx }]; #IO_L7P_T1_AD6P_35 Sch=uart_txd_in
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[5].INV}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[6].INV}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[7].INV}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[8].INV}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells design_1_i/not_series_0/inst/inverted_bit_reg]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells design_1_i/not_series_0/inst/start_reg]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[48].INV}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[25].INV}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[14].INV}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[11].INV}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[12].INV}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[17].INV}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[19].INV}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[21].INV}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[23].INV}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[27].INV}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[29].INV}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[31].INV}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[35].INV}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[39].INV}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[3].INV}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[42].INV}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[43].INV}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[46].INV}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[36].INV}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[2].INV}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[28].INV}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[9].INV}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[49].INV}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[4].INV}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[44].INV}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[20].INV}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[16].INV}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[0].INV}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[10].INV}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[13].INV}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[15].INV}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[18].INV}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[1].INV}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[22].INV}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[30].INV}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[32].INV}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[33].INV}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[37].INV}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[40].INV}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[45].INV}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[47].INV}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[41].INV}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[38].INV}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[34].INV}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[24].INV}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/not_series_0/inst/genblk1[26].INV}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[5].INV}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[6].INV}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[7].INV}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[8].INV}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y63 [get_cells design_1_i/not_series_0/inst/inverted_bit_reg]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y63 [get_cells design_1_i/not_series_0/inst/start_reg]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[48].INV}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[25].INV}]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[14].INV}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[11].INV}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[12].INV}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[17].INV}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[19].INV}]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[21].INV}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[23].INV}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[27].INV}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[29].INV}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[31].INV}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[35].INV}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[39].INV}]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[3].INV}]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[42].INV}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[43].INV}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[46].INV}]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[36].INV}]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[2].INV}]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[28].INV}]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[9].INV}]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[49].INV}]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[4].INV}]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[44].INV}]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[20].INV}]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[16].INV}]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[0].INV}]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[10].INV}]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[13].INV}]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[15].INV}]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[18].INV}]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[1].INV}]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[22].INV}]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[30].INV}]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[32].INV}]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[33].INV}]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[37].INV}]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[40].INV}]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[45].INV}]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y63 [get_cells {design_1_i/not_series_0/inst/genblk1[47].INV}]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[41].INV}]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y62 [get_cells {design_1_i/not_series_0/inst/genblk1[38].INV}]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y60 [get_cells {design_1_i/not_series_0/inst/genblk1[34].INV}]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[24].INV}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y61 [get_cells {design_1_i/not_series_0/inst/genblk1[26].INV}]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells design_1_i/modern_sensible_0/inst/FF1]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5FF [get_cells design_1_i/modern_sensible_0/inst/FF2]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells design_1_i/modern_sensible_0/inst/FF3]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells design_1_i/modern_sensible_0/inst/XOR1]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y63 [get_cells design_1_i/modern_sensible_0/inst/FF1]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y64 [get_cells design_1_i/modern_sensible_0/inst/FF2]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y62 [get_cells design_1_i/modern_sensible_0/inst/FF3]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y62 [get_cells design_1_i/modern_sensible_0/inst/XOR1]
