# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Nexys-4-DDR-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BinToBCD_0_0/design_1_BinToBCD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BinToBCD_0_0 || ORIG_REF_NAME==design_1_BinToBCD_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DisplayController_0_0/design_1_DisplayController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DisplayController_0_0 || ORIG_REF_NAME==design_1_DisplayController_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_temp_catcher_0_0/design_1_temp_catcher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_temp_catcher_0_0 || ORIG_REF_NAME==design_1_temp_catcher_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_modern_sensible_0_0/design_1_modern_sensible_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_modern_sensible_0_0 || ORIG_REF_NAME==design_1_modern_sensible_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not_series_0_0/design_1_not_series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not_series_0_0 || ORIG_REF_NAME==design_1_not_series_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sensor_stream_0_0/design_1_sensor_stream_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sensor_stream_0_0 || ORIG_REF_NAME==design_1_sensor_stream_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_tx_0_0/design_1_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_uart_tx_0_0 || ORIG_REF_NAME==design_1_uart_tx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controller_controller_0_0/design_1_controller_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_controller_controller_0_0 || ORIG_REF_NAME==design_1_controller_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_failure_holder_0_0/design_1_failure_holder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_failure_holder_0_0 || ORIG_REF_NAME==design_1_failure_holder_0_0} -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/Aging/Vivado Projects/aging-study/aging-study.gen/sources_1/bd/design_1/design_1_ooc.xdc
