set_property SRC_FILE_INFO {cfile:/home/dan-alencar/Documents/GitHub/IC-Aging-Environment/aging_study_ultrascale/aging_study_ultrascale.srcs/constrs_1/new/aging_ultrascale.xdc rfile:../../../aging_study_ultrascale.srcs/constrs_1/new/aging_ultrascale.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD20 [get_ports sys_clk_p]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE20 [get_ports sys_clk_n]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W26 [get_ports rx]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y26 [get_ports tx]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL EFF [get_cells aging_sensor/FF1]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF2 [get_cells aging_sensor/FF3]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells aging_sensor/XOR1]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF2 [get_cells aging_sensor/FF2]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells aging_sensor/FF1]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y156 [get_cells aging_sensor/FF3]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y156 [get_cells aging_sensor/XOR1]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells aging_sensor/FF2]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {critical_path/genblk1[19].INV}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[2].INV}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[0].INV}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {critical_path/genblk1[20].INV}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[22].INV}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[4].INV}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[6].INV}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[39].INV}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL G6LUT [get_cells {critical_path/genblk1[40].INV}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E5LUT [get_cells {critical_path/genblk1[42].INV}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[44].INV}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[31].INV}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[33].INV}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {critical_path/genblk1[35].INV}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {critical_path/genblk1[37].INV}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {critical_path/genblk1[24].INV}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {critical_path/genblk1[26].INV}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[28].INV}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {critical_path/genblk1[8].INV}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A5LUT [get_cells {critical_path/genblk1[46].INV}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[48].INV}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL G6LUT [get_cells {critical_path/genblk1[11].INV}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[12].INV}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[15].INV}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[17].INV}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL G6LUT [get_cells {critical_path/genblk1[1].INV}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F5LUT [get_cells {critical_path/genblk1[3].INV}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {critical_path/genblk1[21].INV}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C5LUT [get_cells {critical_path/genblk1[23].INV}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {critical_path/genblk1[18].INV}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL G6LUT [get_cells {critical_path/genblk1[29].INV}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[30].INV}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[25].INV}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[36].INV}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {critical_path/genblk1[38].INV}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[32].INV}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H5LUT [get_cells {critical_path/genblk1[45].INV}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[41].INV}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {critical_path/genblk1[43].INV}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[34].INV}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {critical_path/genblk1[27].INV}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL G6LUT [get_cells {critical_path/genblk1[5].INV}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[7].INV}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5LUT [get_cells {critical_path/genblk1[9].INV}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL G5LUT [get_cells {critical_path/genblk1[47].INV}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL E6LUT [get_cells {critical_path/genblk1[49].INV}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL H6LUT [get_cells {critical_path/genblk1[10].INV}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL G6LUT [get_cells {critical_path/genblk1[13].INV}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[14].INV}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL F6LUT [get_cells {critical_path/genblk1[16].INV}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[19].INV}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[2].INV}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[0].INV}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[20].INV}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells {critical_path/genblk1[22].INV}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y156 [get_cells {critical_path/genblk1[4].INV}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y156 [get_cells {critical_path/genblk1[6].INV}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y159 [get_cells {critical_path/genblk1[39].INV}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y159 [get_cells {critical_path/genblk1[40].INV}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[42].INV}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y156 [get_cells {critical_path/genblk1[44].INV}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y157 [get_cells {critical_path/genblk1[31].INV}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y158 [get_cells {critical_path/genblk1[33].INV}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[35].INV}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y159 [get_cells {critical_path/genblk1[37].INV}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[24].INV}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells {critical_path/genblk1[26].INV}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y157 [get_cells {critical_path/genblk1[28].INV}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells {critical_path/genblk1[8].INV}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[46].INV}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X39Y157 [get_cells {critical_path/genblk1[48].INV}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[11].INV}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y156 [get_cells {critical_path/genblk1[12].INV}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[15].INV}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X39Y157 [get_cells {critical_path/genblk1[17].INV}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[1].INV}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[3].INV}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[21].INV}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells {critical_path/genblk1[23].INV}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[18].INV}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y157 [get_cells {critical_path/genblk1[29].INV}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y157 [get_cells {critical_path/genblk1[30].INV}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells {critical_path/genblk1[25].INV}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y158 [get_cells {critical_path/genblk1[36].INV}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y159 [get_cells {critical_path/genblk1[38].INV}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y158 [get_cells {critical_path/genblk1[32].INV}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y156 [get_cells {critical_path/genblk1[45].INV}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y159 [get_cells {critical_path/genblk1[41].INV}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y156 [get_cells {critical_path/genblk1[43].INV}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X42Y158 [get_cells {critical_path/genblk1[34].INV}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells {critical_path/genblk1[27].INV}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y156 [get_cells {critical_path/genblk1[5].INV}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y156 [get_cells {critical_path/genblk1[7].INV}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X41Y157 [get_cells {critical_path/genblk1[9].INV}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[47].INV}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[49].INV}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y157 [get_cells {critical_path/genblk1[10].INV}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y156 [get_cells {critical_path/genblk1[13].INV}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X40Y156 [get_cells {critical_path/genblk1[14].INV}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X39Y157 [get_cells {critical_path/genblk1[16].INV}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets sys_clk_in]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports fpga_button] -to [all_registers]
