#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jan 20 15:53:44 -03 2025
# SW Build 5164865 on Thu Sep  5 14:36:28 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sim_behav -key {Behavioral:sim_1:Functional:sim} -tclbatch sim.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim sim_behav -key {Behavioral:sim_1:Functional:sim} -tclbatch sim.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

