#####################################################################
# Extract portable fixed-route constraints from a routed checkpoint.
#
# Environment:
#   FIXED_PNR_DCP  Input checkpoint. Default: references/fixed_pnr.dcp
#   FIXED_PNR_XDC  Output XDC. Default: src/constraints/fixed_pnr_constraints.xdc
#####################################################################

set script_dir [file dirname [file normalize [info script]]]
set project_root [file normalize [file join $script_dir ".."]]

proc env_or_default {name default_value} {
    if {[info exists ::env($name)] && $::env($name) ne ""} {
        return $::env($name)
    }
    return $default_value
}

set checkpoint_file [file normalize [env_or_default FIXED_PNR_DCP [file join $project_root "references/fixed_pnr.dcp"]]]
set output_file [file normalize [env_or_default FIXED_PNR_XDC [file join $project_root "src/constraints/fixed_pnr_constraints.xdc"]]]
set full_xdc_file [file join $project_root "references/fixed_pnr_full_from_checkpoint.xdc"]

if {![file exists $checkpoint_file]} {
    error "Checkpoint not found: $checkpoint_file"
}

puts "Opening fixed PnR checkpoint: $checkpoint_file"
open_checkpoint $checkpoint_file

# Pure-RTL hierarchy (nexys4_aging_top):
#   u_sensor  — modern_sensible instance
#   u_adder   — adder_canary instance (u_adder/u_canary = ripple_adder)
set patterns [list \
    "u_sensor/*" \
    "u_adder/u_canary/*" \
]

set selected_cells [list]
foreach pattern $patterns {
    foreach cell [get_cells -hier -quiet $pattern] {
        lappend selected_cells $cell
    }
}
set selected_cells [lsort -unique $selected_cells]

set selected_nets [list]
foreach cell $selected_cells {
    foreach pin [get_pins -quiet -of_objects $cell] {
        foreach net [get_nets -quiet -of_objects $pin] {
            lappend selected_nets $net
        }
    }
}
set selected_nets [lsort -unique $selected_nets]

set out [open $output_file w]
puts $out "# Fixed physical constraints extracted from $checkpoint_file"
puts $out "# Generated by scripts/extract_fixed_pnr_constraints.tcl"
puts $out ""

foreach cell $selected_cells {
    set bel [get_property BEL $cell]
    if {$bel ne ""} {
        puts $out [format {set_property BEL %s [get_cells {%s}]} $bel $cell]
    }
}
puts $out ""

foreach cell $selected_cells {
    set loc [get_property LOC $cell]
    if {$loc ne ""} {
        puts $out [format {set_property LOC %s [get_cells {%s}]} $loc $cell]
    }
}
puts $out ""

foreach net $selected_nets {
    set fixed_route [get_property FIXED_ROUTE $net]
    if {$fixed_route ne ""} {
        puts $out [format {set_property FIXED_ROUTE {%s} [get_nets {%s}]} $fixed_route $net]
    }
}
close $out

catch {write_xdc -force $full_xdc_file}

puts "Wrote fixed PnR constraints: $output_file"
puts "Wrote full checkpoint XDC snapshot when supported: $full_xdc_file"
